// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/stanchan/fusion-solr/proto/fusion/fusion.proto

/*
Package go_micro_srv_fusion is a generated protocol buffer package.

It is generated from these files:
	github.com/stanchan/fusion-solr/proto/fusion/fusion.proto

It has these top-level messages:
	Message
	Request
	Response
	StreamingRequest
	StreamingResponse
	Ping
	Pong
*/
package go_micro_srv_fusion

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Say string `protobuf:"bytes,1,opt,name=say" json:"say,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamingRequest struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *StreamingRequest) Reset()                    { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()               {}
func (*StreamingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *StreamingResponse) Reset()                    { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()               {}
func (*StreamingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke int64 `protobuf:"varint,1,opt,name=stroke" json:"stroke,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke int64 `protobuf:"varint,1,opt,name=stroke" json:"stroke,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.fusion.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.fusion.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.fusion.Response")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.fusion.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.fusion.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.fusion.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.fusion.Pong")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Fusion service

type FusionClient interface {
	Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...grpc.CallOption) (Fusion_StreamClient, error)
	PingPong(ctx context.Context, opts ...grpc.CallOption) (Fusion_PingPongClient, error)
}

type fusionClient struct {
	cc *grpc.ClientConn
}

func NewExampleClient(cc *grpc.ClientConn) ExampleClient {
	return &fusion{cc}
}

func (c *fusion) Call(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/go.micro.srv.fusion.Fusion/Call", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fusionClient) Stream(ctx context.Context, in *StreamingRequest, opts ...grpc.CallOption) (Fusion_StreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Fusion_serviceDesc.Streams[0], c.cc, "/go.micro.srv.fusion.Fusion/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &fusionStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Fusion_StreamClient interface {
	Recv() (*StreamingResponse, error)
	grpc.ClientStream
}

type fusionStreamClient struct {
	grpc.ClientStream
}

func (x *fusionStreamClient) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fusionClient) PingPong(ctx context.Context, opts ...grpc.CallOption) (Fusion_PingPongClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Fusion_serviceDesc.Streams[1], c.cc, "/go.micro.srv.fusion.Fusion/PingPong", opts...)
	if err != nil {
		return nil, err
	}
	x := &fusionPingPongClient{stream}
	return x, nil
}

type Fusion_PingPongClient interface {
	Send(*Ping) error
	Recv() (*Pong, error)
	grpc.ClientStream
}

type fusionPingPongClient struct {
	grpc.ClientStream
}

func (x *fusionPingPongClient) Send(m *Ping) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fusionPingPongClient) Recv() (*Pong, error) {
	m := new(Pong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Fusion service

type FusionServer interface {
	Call(context.Context, *Request) (*Response, error)
	Stream(*StreamingRequest, Fusion_StreamServer) error
	PingPong(Fusion_PingPongServer) error
}

func RegisterFusionServer(s *grpc.Server, srv FusionServer) {
	s.RegisterService(&_Fusion_serviceDesc, srv)
}

func _Fusion_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FusionServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.srv.fusion.Fusion/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FusionServer).Call(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fusion_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamingRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FusionServer).Stream(m, &fusionStreamServer{stream})
}

type Fusion_StreamServer interface {
	Send(*StreamingResponse) error
	grpc.ServerStream
}

type fusionStreamServer struct {
	grpc.ServerStream
}

func (x *fusionStreamServer) Send(m *StreamingResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Fusion_PingPong_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FusionServer).PingPong(&fusionPingPongServer{stream})
}

type Fusion_PingPongServer interface {
	Send(*Pong) error
	Recv() (*Ping, error)
	grpc.ServerStream
}

type fusionPingPongServer struct {
	grpc.ServerStream
}

func (x *fusionPingPongServer) Send(m *Pong) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fusionPingPongServer) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Fusion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.srv.fusion.Fusion",
	HandlerType: (*FusionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _Fusion_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Fusion_Stream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PingPong",
			Handler:       _Fusion_PingPong_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/stanchan/fusion-solr/proto/fusion/fusion.proto",
}

func init() {
	proto.RegisterFile("github.com/stanchan/fusion-solr/proto/fusion/fusion.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4b, 0x2b, 0x31,
	0x10, 0xc6, 0x1b, 0xda, 0xd7, 0xf6, 0xcd, 0xa9, 0x86, 0x22, 0xb2, 0xda, 0x22, 0x39, 0x68, 0xbd,
	0x64, 0x8b, 0x5e, 0xbd, 0x89, 0xe8, 0x45, 0x90, 0xf5, 0xec, 0x21, 0x2d, 0x43, 0x5c, 0x6c, 0x92,
	0x9a, 0x49, 0x8b, 0xfe, 0xed, 0x5e, 0x64, 0xb3, 0x59, 0x11, 0xd9, 0xc5, 0x53, 0x66, 0xe6, 0xf7,
	0x7d, 0xc3, 0xcc, 0x10, 0xb8, 0xd6, 0x65, 0x78, 0xd9, 0xad, 0xe4, 0xda, 0x99, 0xdc, 0x94, 0x6b,
	0xef, 0x72, 0x7c, 0x57, 0x66, 0xbb, 0x41, 0xca, 0x09, 0xfd, 0x1e, 0x7d, 0xbe, 0xf5, 0x2e, 0x7c,
	0x57, 0x9b, 0x57, 0xc6, 0x2a, 0x9f, 0x6a, 0x27, 0xa3, 0x4b, 0x92, 0xdf, 0xcb, 0xc4, 0xc4, 0x31,
	0x8c, 0x1e, 0x90, 0x48, 0x69, 0xe4, 0x13, 0xe8, 0x93, 0xfa, 0x38, 0x62, 0xa7, 0x6c, 0xf1, 0xbf,
	0xa8, 0x42, 0x31, 0x83, 0x51, 0x81, 0x6f, 0x3b, 0xa4, 0xc0, 0x39, 0x0c, 0xac, 0x32, 0x98, 0x68,
	0x8c, 0xc5, 0x09, 0x8c, 0x0b, 0xa4, 0xad, 0xb3, 0x14, 0xcd, 0x86, 0x74, 0x63, 0x36, 0xa4, 0xc5,
	0x02, 0x26, 0x4f, 0xc1, 0xa3, 0x32, 0xa5, 0xd5, 0x4d, 0x97, 0x29, 0xfc, 0x5b, 0xbb, 0x9d, 0x0d,
	0x51, 0xd7, 0x2f, 0xea, 0x44, 0x5c, 0xc0, 0xc1, 0x0f, 0x65, 0x6a, 0xd8, 0x2e, 0x9d, 0xc3, 0xe0,
	0xb1, 0xb4, 0x9a, 0x1f, 0xc2, 0x90, 0x82, 0x77, 0xaf, 0x98, 0x70, 0xca, 0x22, 0x77, 0xdd, 0xfc,
	0xf2, 0x93, 0xc1, 0xe8, 0xb6, 0x5e, 0x9d, 0xdf, 0xc1, 0xe0, 0x46, 0x6d, 0x36, 0x7c, 0x26, 0xdb,
	0x2e, 0x23, 0xd3, 0xcc, 0xd9, 0xbc, 0x0b, 0xd7, 0x83, 0x8a, 0x1e, 0x7f, 0x86, 0x61, 0x3d, 0x3f,
	0x3f, 0x6b, 0xd7, 0xfe, 0xbe, 0x43, 0x76, 0xfe, 0xa7, 0xae, 0x69, 0xbe, 0x64, 0xfc, 0x1e, 0xc6,
	0xd5, 0xce, 0x71, 0xaf, 0xac, 0xdd, 0x58, 0xf1, 0xac, 0x8b, 0x39, 0xab, 0x45, 0x6f, 0xc1, 0x96,
	0x6c, 0x35, 0x8c, 0x3f, 0xe1, 0xea, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x6d, 0x30, 0x6b, 0x49,
	0x02, 0x00, 0x00,
}
